<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="CliFx" Version="2.3.6" />
    <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageVersion Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

</Project>