<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CliFx" Version="3.0.1" />
    <PackageVersion Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.401" />
    <PackageVersion Include="Roslynator.Analyzers" Version="5.0.0" />
    <PackageVersion Include="Roslynator.CodeAnalysis.Analyzers" Version="5.0.0" />
    <PackageVersion Include="Roslynator.Formatting.Analyzers" Version="5.0.0" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>
</Project>